use_frameworks!

target 'UIViewControllerTransitions_Example' do
  pod 'UIViewControllerTransitions', :path => '../'

  target 'UIViewControllerTransitions_Tests' do
    inherit! :search_paths

    
  end
end
